# Create dev environment
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  'Snowflake_pool'

steps:

# Create new database shell for development 
- task: CmdLine@2
  inputs:
<<<<<<< HEAD
    script: 'snowsql -a va_demo32.us-east-1 -u devops_user --filename $(agent.builddirectory)/s/Create_Dev_Database.sql'
    workingDirectory: '/home/rshetler/bin'
=======
    script: 'snowsql -a va_demo32.us-east-1 -u devops_user --filename $(agent.builddirectory)/s/Create_Dev_database.sql'
    workingDirectory: '/home/rshetler/bin'
>>>>>>> 804d4a6ec71b7e39c65b6954ff7d311ff8091a26
