# Promote all changes from QA to prod, refresh dev 
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  'Snowflake_pool'

steps:

# promote changes from QA to prod 
- task: CmdLine@2
  inputs:
    script: 'snowsql -a va_demo32.us-east-1 -u devops_user --filename $(agent.builddirectory)/s/Promote_to_PROD.sql'
    workingDirectory: '/home/rshetler/bin'

# Drop current dev clone environment and create new one after prod is refreshed
- task: CmdLine@2
  inputs:
    script: 'snowsql -a va_demo32.us-east-1 -u devops_user --filename $(agent.builddirectory)/s/Refresh_Dev_Environment.sql'
    workingDirectory: '/home/rshetler/bin'