# Create dev environment
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - v2

pool:
  'Snowflake_pool'

steps:

# create new clone of production for Dev environment 
- task: CmdLine@2
  inputs:
    script: 'snowsql -a va_demo32.us-east-1 -u devops_user --filename $(agent.builddirectory)/s/Create_Dev_Database.sql'
    workingDirectory: '/home/rshetler/bin'
