# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  'Snowflake_pool'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Create new database shell for development 
- task: CmdLine@2
  inputs:
    script: 'snowsql -a va_demo32.us-east-1 -u devops_user --filename $(agent.builddirectory)/s/Create_DevOps_DemoDB.sql'
    workingDirectory: '/home/rshetler/bin'
