# Create QA environment and promote dev changes
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  'Snowflake_pool'

steps:

# Run script to promote to QA
- task: CmdLine@2
  inputs:
    script: 'snowsql -a va_demo32.us-east-1 -u devops_user --filename $(agent.builddirectory)/s/Create_QA_Database.sql'
    workingDirectory: '/home/rshetler/bin'